---
- name: OS Update
  hosts: all
  connection: local
  gather_facts: false

  tasks:
  - name: create_newfile
    ansible.builtin.file:
      path: "/home/user/Ansible/other/evidence/{{ inventory_hostname }}_{{ evidence_filename }}.txt"
      state: touch

  - debug:
      msg:
        - "OSバージョン:{{ FinalOSVer }} ==> {{ nowOSVer }}"
        - "アップグレードを実行します。"

# ==============================================1段階の塊=============================================
  - name: confirm
    pause: prompt="2号機のダウングレードを実施しますか？{{ OSVer4_latest }} ==> {{ OSVer3_base }} ==> {{ OSVer3_latest }} ==> {{ OSVer2_base }} ==> {{ OSVer2_latest }} (y/n)"
    register: yn

  - name: abort
    fail: msg="nが入力されたため中止します。"
    when: yn.user_input != 'y'
    run_once: true

  - name: Suspend_PA2_01
    include_role:
      name: 04_suspendHA
    when: inventory_hostname == 'PA2'

  - name: HAcheck
    include_role:
      name: 09_CheckHA

  - name: Vercheck
    include_role:
      name: 10_assertver
    when: inventory_hostname == 'PA2'
    vars:
      - version: '{{ OSVer4_latest }}'

  - name: Update_PA2_01
    include_role:
      name: 06_OSupgrade
    when: inventory_hostname == 'PA2'
    vars:
      - version: '{{ item.OS | default(omit) }}'
    with_items:
      - "{{ Update43 }}"

  - name: Vercheck
    include_role:
      name: 10_assertver
    when: inventory_hostname == 'PA2'
    vars:
      - version: '{{ OSVer2_latest }}'

# -----------------------------------------------------------------------------

  - name: confirm
    pause: prompt="1号機のダウングレードを実施しますか？ {{ OSVer4_latest }} ==> {{ OSVer3_base }} ==> {{ OSVer3_latest }} ==> {{ OSVer2_base }} ==> {{ OSVer2_latest }}  ==> {{ OSVer1_base }} ==> {{ OSVer1_latest }} ==> {{ nowOSVer_base }} ==> {{ nowOSVer_latest }} (y/n)"
    register: yn

  - name: abort
    fail: msg="nが入力されたため中止します。"
    when: yn.user_input != 'y'
    run_once: true

  - name: Suspend_PA1_01
    include_role:
      name: 04_suspendHA
    when: inventory_hostname == 'PA1'

  - name: Vercheck
    include_role:
      name: 10_assertver
    when: inventory_hostname == 'PA2'
    vars:
      - version: '{{ OSVer4_latest }}'

  - name: Update_PA1_01
    include_role:
      name: 06_OSupgrade
    when: inventory_hostname == 'PA1'
    vars:
      - version: '{{ item.OS | default(omit) }}'
    with_items:
      - "{{ Update41 }}"

  - name: Vercheck
    include_role:
      name: 10_assertver
    when: inventory_hostname == 'PA1'
    vars:
      - version: '{{ nowOSver_latest }}'

# ------------------------------------------------------------------------------------------------

  - name: confirm
    pause: prompt="2号機のダウングレードを実施しますか？{{ OSVer2_latest }} ==> {{ OSVer3 }} ==> {{ OSVer3_latest }} ==> {{ OSVer4 }} ==> {{ OSVer4_latest }} (y/n)"
    register: yn

  - name: abort
    fail: msg="nが入力されたため中止します。"
    when: yn.user_input != 'y'
    run_once: true

  - name: Suspend_PA2_01
    include_role:
      name: 04_suspendHA
    when: inventory_hostname == 'PA2'

  - name: HAcheck
    include_role:
      name: 09_CheckHA

  - name: Vercheck
    include_role:
      name: 10_assertver
    when: inventory_hostname == 'PA2'
    vars:
      - version: '{{ OSVer2_latest }}'

  - name: Update_PA2_01
    include_role:
      name: 06_OSupgrade
    when: inventory_hostname == 'PA2'
    vars:
      - version: '{{ item.OS | default(omit) }}'
    with_items:
      - "{{ Update21 }}"

  - name: Vercheck
    include_role:
      name: 10_assertver
    when: inventory_hostname == 'PA2'
    vars:
      - version: '{{ OSVer4_latest }}'

  - name: CheckOSVer
    include_role:
      name: 08_CheckOS
# ==============================================塊=============================================


  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
# ----suspend切り替わり----
    Update43:
      - OS: '{{ OSVer3_base }}'
      - OS: '{{ OSVer3_latest }}'
      - OS: '{{ OSVer2_base }}'
      - OS: '{{ OSVer2_latest }}'
# ----suspend切り替わり----
    Update41:
      - OS: '{{ OSVer3_base }}'
      - OS: '{{ OSVer3_latest }}'
      - OS: '{{ OSVer2_base }}'
      - OS: '{{ OSVer2_latest }}'
      - OS: '{{ OSVer1_base }}'
      - OS: '{{ OSVer1_latest }}'
      - OS: '{{ nowOSVer_base }}'
      - OS: '{{ nowOSVer_latest }}'
# ----suspend切り替わり----

    Update21:
      - OS: '{{ OSVer1_base }}'
      - OS: '{{ OSVer1_latest }}'
      - OS: '{{ nowOSVer_base }}'
      - OS: '{{ nowOSVer_latest }}'
      
